### ISSUE TITLE
TODO - Coding: Condition annotation verification

### ISSUE THREAD

**Issue by callahantiff** [callahantiff/Biolater#4]
**Needed Scripts:** verify code to create condition code mapping
- [x] Map raw SNOMED-CT to CUI and Semantic Types (UMLS API to retrieve both OR download MRCONSO and SEMTYPE files from UMLS)
- [x] Code to get synonyms, labels, and defs from ontologies (write code to download data)
- [x] Similarity code 

**Inputs:** pandas data frame or results of SQL query
**Action:** maps clinical concepts to different open biomedical ontologies (OBOs)
**Output:** csv file with suggested mappings between condition codes and OBOs

**Comment by callahantiff** [comment]
Update mappings to be primarily to identifier

**Comment by callahantiff** [comment]
**UPDATE:** 2,000 randomly selected terms are being mapped by a resident with medical coding experience. The expected date when this will be complete is 04/29/2019. 

[This](https://paper.dropbox.com/doc/PEDSnet-OMOP-Condition-Annotation-Verification--AaPe9f5gcWDRQGgLj1UP3L95Ag-XSgIZ3tUDYNo6vQ5cwqt5) documentation was added to help map these terms.

**Comment by callahantiff** [comment]
- [ ] Update all fracture terms and work with HPO team to expand fracture sub-types ([HPO issue](https://github.com/obophenotype/human-phenotype-ontology/issues/3889))

**Comment by callahantiff** [comment]
- [x] The first iteration of condition code mapping update is (finally) complete! See stats below. 🎉 

Unique diagnoses (n=29,128) 

Mapping Type | Count
:--: | :--: 
Automatically Mapped | 6,285
Automatically Mapped - Ancestor | 4,893
Manually Mapped | 9,768
Manually Mapped - Synonym | 3,613
Manually Mapped - Constructor | 14,058
UnMapped | 19,639  

Final mapping can be accessed [here](https://docs.google.com/spreadsheets/d/1OCjHTezhRJ0HjpX9BaGwV_2im9o_ChB63Ul8gOce8jE/edit#gid=754118077).

**Comment by callahantiff** [comment]
> * [ ]  Update all fracture terms and work with HPO team to expand fracture sub-types ([HPO issue](https://github.com/obophenotype/human-phenotype-ontology/issues/3889))

**UPDATE:** Not moving forward with this at this time.
