### ISSUE TITLE
TODO - Mapping: Verify Lab test mapping

### ISSUE THREAD

**Issue by callahantiff** [callahantiff/Biolater#6]
Verify the last few lab test results with Dr. Vasilevsky.

**Comment by callahantiff** [comment]
- [ ] Do a final check of ll terms
- [ ] Verify the terms that have been requested as new with HPO
- [ ] Ask NV to peek at anything needing expert opinion

**Comment by callahantiff** [comment]
- [x] Lab test code mapping update is complete! See stats below. 🎉 

Unique lab tests (n=902) 
Unique lab test results (n=2,734)

Mapping Type | Count
:--: | :--: 
Manually Mapped | 2593
UnMapped | 141

Final mapping can be accessed [here](https://docs.google.com/spreadsheets/d/1OCjHTezhRJ0HjpX9BaGwV_2im9o_ChB63Ul8gOce8jE/edit#gid=1908224033&range=B1:R2735).
